### ISSUE TITLE
Error uploading iOS XCUITests

### ISSUE THREAD

**Issue by dasarijit95** [xamarinhq/test-cloud-uploader#45]
Getting error while trying to upload my tests to Xamarin Test cloud
`aridas ~/Desktop: /Users/aridas/Desktop/xtc/xtc xcuitest a502145530ba208c746e6a0014700f60 --devices eb8b0f9b --series "beta" --locale "en_US" --user <email> --workspace /Users/aridas/Desktop/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos`

This fails with the following:
`Error: Error while executing command xcuitest: Unable to copy application bundle into Payload dir with command:\n
ditto /Users/aridas/Desktop/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/MSEG Tasks.app /var/folders/cr/vg4d9yts4w125j4nw0vfw3c40000gq/T/lgf3uatr.u14/Payload/MSEG Tasks.app`

 Any help would be greatly appreciated. Thanks in advance.

**Comment by dasarijit95** [comment]
With the debug flag on

`fail: Microsoft.Xtc.Cli.Program[0]
      Error while executing command xcuitest: Unable to copy application bundle into Payload dir with command:\n
                          ditto /Users/aridas/Desktop/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/MSEG Tasks.app /var/folders/cr/vg4d9yts4w125j4nw0vfw3c40000gq/T/pwj0zpwv.vr5/Payload/MSEG Tasks.app
dbug: Microsoft.Xtc.Cli.Program[0]
      System.Exception: Unable to copy application bundle into Payload dir with command:\n
                          ditto /Users/aridas/Desktop/Build/Intermediates/CodeCoverage/Products/Debug-iphoneos/MSEG Tasks.app /var/folders/cr/vg4d9yts4w125j4nw0vfw3c40000gq/T/pwj0zpwv.vr5/Payload/MSEG Tasks.app
         at Microsoft.Xtc.TestCloud.Utilities.FileHelper.ArchiveAppBundle(String appBundlePath) in /Users/Shared/Jenkins/jobs/Uploader master/workspace/Xtc/src/Xtc.TestCloud/Utilities/FileHelper.cs:line 103
         at Microsoft.Xtc.TestCloud.Commands.UploadXCUITestsCommandOptions.get_AppFile() in /Users/Shared/Jenkins/jobs/Uploader master/workspace/Xtc/src/Xtc.TestCloud/Commands/UploadXCUITestsCommandOptions.cs:line 65
         at Microsoft.Xtc.TestCloud.Commands.UploadXCUITestCommandExecutor.ValidateOptions() in /Users/Shared/Jenkins/jobs/Uploader master/workspace/Xtc/src/Xtc.TestCloud/Commands/UploadXCUITestCommandExecutor.cs:line 22
         at Microsoft.Xtc.TestCloud.Commands.UploadXTCTestCommandExecutor.<ExecuteAsync>d__27.MoveNext() in /Users/Shared/Jenkins/jobs/Uploader master/workspace/Xtc/src/Xtc.TestCloud/Commands/UploadXTCTestCommandExecutor.cs:line 122`

**Comment by nvorontsov** [comment]
I had the same error message . I had a space in my app name (e.g: "My App"). I changed it to MyApp in scheme and target and it solved the issue.
